import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer";
import Image from "next/image"
import Button from "@/components/Button";

const inter = Poppins({ subsets: ["latin"], weight: ["500", "700"] });

export const metadata: Metadata = {
  title: "Shortly | URL Shortener",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} pt-10 md:pt-12`}>
        <Header />
        <div className="">
          <main className="pb-[168px] px-6">
            <div className="overflow-hidden pb-[37px]">
              <Image
                src={"/illustration-working.svg"}
                alt="hero image"
                width={733}
                height={482}
                className="relative"
              />
            </div>
            <div className="flex flex-col gap-[15px]">
              <h1 className="text-[42px] font-bold text-[#34313D] leading-[48px] text-center">
                More than just shorter links
              </h1>
              <p className="text-[#9E9AA8] font-medium text-lg leading-[30px] tracking-[0.12px] text-center mb-5">
                {"Build your brand’s recognition and get detailed insights on how your links are performing."}
              </p>
              <div className="px-[65px] font-bold text-white">
                <Button text="Get Started" />
              </div>
            </div>
          </main>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
